version: .{build}
clone_folder: c:\work\messagepack

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

os: Visual Studio 2017

environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true
  GITHUB_USER:
    secure: 5NfHPjw31vB/XxJqwpHp3cl3n/9F7PTUVXhMIqRSDJE=
  GITHUB_PASSWORD:
    secure: 9gArAAMTQRHIsSZcJ+87GM+kaSfsBlouuFHtBR1hWBY=

#cache:
#  - c:\tmp\cake\tools -> appveor.yml

build_script:
  - ps: ./build.ps1 -verbosity diagnostic

test: off

artifacts:
  - path: artifacts/packages/*.nupkg
    name: Nugets

deploy:
  - provider: NuGet
    api_key:
      secure: GhGzYN5/LaDMZdwRi+rbwcG20q3pqhoRmwsVGwRD2sXzsr+xaH6p34OcPsGcn3JP
    on:
      branch:
        - develop
        - /release\/v.*/
        - /releases.*/
        - /hotfixes.*/
