version: .{build}
clone_folder: c:\work\messagepack

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

os: Visual Studio 2019

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  coveralls_repo_token:
    secure: PPV4OTsE0mqUJQ5UXY8dKJnifv+488XNxe7rtyUbiYJNMgvOooUZvGeSxhsOIJmJ
  CAKE_SETTINGS_SKIPVERIFICATION: true
  GITHUB_USER:
    secure: 5NfHPjw31vB/XxJqwpHp3cl3n/9F7PTUVXhMIqRSDJE=
  GITHUB_PASSWORD:
    secure: 9gArAAMTQRHIsSZcJ+87GM+kaSfsBlouuFHtBR1hWBY=

#install:
#  - appveyor DownloadFile https://dot.net/v1/dotnet-install.ps1 -FileName dotnet-install.ps1
#  - ps: ./dotnet-install.ps1 -Version 3.0.100-preview9-014004 -InstallDir "C:\Program Files\dotnet"
  
build_script:
  - ps: ./build.ps1

test: off

artifacts:
  - path: artifacts/packages/*.nupkg
    name: Nugets

deploy:
  - provider: NuGet
    api_key:
      secure: GhGzYN5/LaDMZdwRi+rbwcG20q3pqhoRmwsVGwRD2sXzsr+xaH6p34OcPsGcn3JP
    on:
      branch:
        - develop
        - /release\/v.*/
        - /releases.*/
        - /hotfixes.*/
