version: .{build}
clone_folder: c:\work\messagepack

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

os: Visual Studio 2019

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  coveralls_repo_token:
    secure: PPV4OTsE0mqUJQ5UXY8dKJnifv+488XNxe7rtyUbiYJNMgvOooUZvGeSxhsOIJmJ
  CAKE_SETTINGS_SKIPVERIFICATION: true
  GITHUB_USER:
    secure: 5NfHPjw31vB/XxJqwpHp3cl3n/9F7PTUVXhMIqRSDJE=
  GITHUB_PASSWORD:
    secure: 9gArAAMTQRHIsSZcJ+87GM+kaSfsBlouuFHtBR1hWBY=

build_script:
  - ps: ./build.ps1

test: off

artifacts:
  - path: artifacts/packages/*.nupkg
    name: Nugets

deploy:
  - provider: NuGet
    name: Pre-release
    api_key:
      secure: UtOq3A67FSX/X2GYpy2sRB0a9xEoguCkjUuo8UTV9svFeVJT//g4IhJiyCtSYq9u
    on:
      branch:
        - develop
        - /release\/v.*/
        - /releases.*/
        - /hotfixes.*/

  - provider: NuGet
    name: Tagged release
    api_key:
      secure: UtOq3A67FSX/X2GYpy2sRB0a9xEoguCkjUuo8UTV9svFeVJT//g4IhJiyCtSYq9u
    on:
      appveyor_repo_tag: true
